apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: bookinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/hupiper/bookinfo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true